// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBLp55Oig304qGLn5zwmhRZDciJEVRqGY',
    appId: '1:22908550346:web:0d0e5124ae1352ecb30833',
    messagingSenderId: '22908550346',
    projectId: 'fir-authen-6afd6',
    authDomain: 'fir-authen-6afd6.firebaseapp.com',
    storageBucket: 'fir-authen-6afd6.firebasestorage.app',
    measurementId: 'G-KBSPQT0HNM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2dgMGPARIWnj-6COTabqYB4ebd7Bc8io',
    appId: '1:22908550346:android:0b89436ea79b00eeb30833',
    messagingSenderId: '22908550346',
    projectId: 'fir-authen-6afd6',
    storageBucket: 'fir-authen-6afd6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBZqZruUjJT-7coakLUfLGxSpNxzkR7xc',
    appId: '1:22908550346:ios:94afb391e267338eb30833',
    messagingSenderId: '22908550346',
    projectId: 'fir-authen-6afd6',
    storageBucket: 'fir-authen-6afd6.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBZqZruUjJT-7coakLUfLGxSpNxzkR7xc',
    appId: '1:22908550346:ios:94afb391e267338eb30833',
    messagingSenderId: '22908550346',
    projectId: 'fir-authen-6afd6',
    storageBucket: 'fir-authen-6afd6.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBLp55Oig304qGLn5zwmhRZDciJEVRqGY',
    appId: '1:22908550346:web:bb11f7b3fca7c214b30833',
    messagingSenderId: '22908550346',
    projectId: 'fir-authen-6afd6',
    authDomain: 'fir-authen-6afd6.firebaseapp.com',
    storageBucket: 'fir-authen-6afd6.firebasestorage.app',
    measurementId: 'G-8LQ2K09R2C',
  );
}
